import Head from "next/head";
import styles from "@/styles/Home.module.scss";
import { Navbar } from "../../components/Navbar";

type Inputs = {
  email: string;
  password: string;
};

export default function Login() {
  

  return (
    <>
      <Head>
        <title>Auth Patterns</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className={styles.main}>
      
      </main>
      
    </>
  );
}
